### ISSUE TITLE
Proxying breaks for characters with only a prefix set as a proxy tag

### ISSUE THREAD

**Issue by xBelladonna** [PlatypodeCode/CinnamonRP#32]
Message proxying is broken for characters with only a prefix set as a proxy tag. Characters with suffixes work, and characters with both a prefix and a suffix also work. No errors at the console, and `console.log`ging all the variables involved in `proxy.js` results in the proper values being displayed so I'm not sure what's going on there. 

![image](https://user-images.githubusercontent.com/47324660/58600057-150dc100-82c2-11e9-9e30-04e18189a8b8.png)

**Comment by BeeFox-sys** [comment]
Fixed!
